FROM python:3.10.7-bullseye

WORKDIR /app
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

COPY /backend ./backend

CMD ["uvicorn", "backend.app:app","--host","0.0.0.0", "--port", "3000"]
EXPOSE 3000