FROM python:3.10.7-bullseye

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

RUN rm requirements.txt

CMD ["uvicorn", "backend.app:app","--host","0.0.0.0", "--port", "3000"]
EXPOSE 3000